### ISSUE TITLE
PPObuffer get函数没有返回值

### ISSUE THREAD

**Issue by youyouzz** [Metro1998/hppo-in-traffic-signal-control#15]
这段代码是不是有问题，没有返回值

def get(self, batch_size):

        obs_buf = self.obs_buf[:self.ptr]
        act_dis_buf = self.act_dis_buf[:self.ptr]
        act_con_buf = self.act_con_buf[:self.ptr]
        adv_buf = self.adv_buf[:self.ptr]
        ret_buf = self.ret_buf[:self.ptr]
        logp_dis_buf = self.logp_dis_buf[:self.ptr]
        logp_con_buf = self.logp_con_buf[:self.ptr]
        ptr_buf = self.ptr_buf[:self.ptr]

        # the next lines implement the normalization trick
        obs_buf = (obs_buf - np.mean(obs_buf)) / np.maximum(np.std(obs_buf), 1e-6)
        # note, we are conducting normalization on Q_function not on reward
        adv_buf = (adv_buf - adv_buf.mean()) / np.maximum(adv_buf.std(), 1e-6)

        sampler = BatchSampler(
            SubsetRandomSampler(range(self.ptr)),
            batch_size,
            drop_last=True
        )

        for indices in sampler:
            yield torch.as_tensor(obs_buf[indices], dtype=torch.float32, device=self.device), \
                  torch.as_tensor(act_dis_buf[indices], dtype=torch.int64, device=self.device), \
                  torch.as_tensor(act_con_buf[indices], dtype=torch.float32, device=self.device), \
                  torch.as_tensor(adv_buf[indices], dtype=torch.float32, device=self.device), \
                  torch.as_tensor(ret_buf[indices], dtype=torch.float32, device=self.device), \
                  torch.as_tensor(logp_dis_buf[indices], dtype=torch.float32, device=self.device), \
                  torch.as_tensor(logp_con_buf[indices], dtype=torch.float32, device=self.device), \
                  torch.as_tensor(ptr_buf[indices], dtype=torch.int64, device=self.device)

        # data = dict(obs=obs_buf, act=act_buf, ret=ret_buf, adv=adv_buf, logp=logp_buf)
        # return {k: torch.as_tensor(v, dtype=torch.float32, device=self.device) for k, v in data.items()}

**Comment by Jingqi-Z** [comment]
> 这段代码是不是有问题，没有返回值
> 
> def get(self, batch_size):
> 
> ```
>     obs_buf = self.obs_buf[:self.ptr]
>     act_dis_buf = self.act_dis_buf[:self.ptr]
>     act_con_buf = self.act_con_buf[:self.ptr]
>     adv_buf = self.adv_buf[:self.ptr]
>     ret_buf = self.ret_buf[:self.ptr]
>     logp_dis_buf = self.logp_dis_buf[:self.ptr]
>     logp_con_buf = self.logp_con_buf[:self.ptr]
>     ptr_buf = self.ptr_buf[:self.ptr]
> 
>     # the next lines implement the normalization trick
>     obs_buf = (obs_buf - np.mean(obs_buf)) / np.maximum(np.std(obs_buf), 1e-6)
>     # note, we are conducting normalization on Q_function not on reward
>     adv_buf = (adv_buf - adv_buf.mean()) / np.maximum(adv_buf.std(), 1e-6)
> 
>     sampler = BatchSampler(
>         SubsetRandomSampler(range(self.ptr)),
>         batch_size,
>         drop_last=True
>     )
> 
>     for indices in sampler:
>         yield torch.as_tensor(obs_buf[indices], dtype=torch.float32, device=self.device), \
>               torch.as_tensor(act_dis_buf[indices], dtype=torch.int64, device=self.device), \
>               torch.as_tensor(act_con_buf[indices], dtype=torch.float32, device=self.device), \
>               torch.as_tensor(adv_buf[indices], dtype=torch.float32, device=self.device), \
>               torch.as_tensor(ret_buf[indices], dtype=torch.float32, device=self.device), \
>               torch.as_tensor(logp_dis_buf[indices], dtype=torch.float32, device=self.device), \
>               torch.as_tensor(logp_con_buf[indices], dtype=torch.float32, device=self.device), \
>               torch.as_tensor(ptr_buf[indices], dtype=torch.int64, device=self.device)
> 
>     # data = dict(obs=obs_buf, act=act_buf, ret=ret_buf, adv=adv_buf, logp=logp_buf)
>     # return {k: torch.as_tensor(v, dtype=torch.float32, device=self.device) for k, v in data.items()}
> ```

代码没问题

**Comment by youyouzz** [comment]
是我的新env的ptr小于了默认的batch size了，然后droplast=true了，导致返回空。。。
