### ISSUE TITLE
Can you provide an environment installation guide?

### ISSUE THREAD

**Issue by twodog0508** [Metro1998/hppo-in-traffic-signal-control#7]
gymnasium.error.NameNotFound: Environment `sumo-rl` doesn't exist.

**Comment by Metro1998** [comment]
I have add the`SUMOEnv.py`in the `env/` folder. Please git pull before and register it locally. 
Refer to https://gymnasium.farama.org/api/registry/ for more information.

**Comment by twodog0508** [comment]
Thank you。But，There are some formatting error in the SUMOEnv.py，such as 
![image](https://github.com/Metro1998/hppo-in-traffic-signal-control/assets/86106824/889ff000-ae22-4634-8494-ea5bfdaf7b7d)

**Comment by twodog0508** [comment]
Thank you very much!

**Comment by ohhhor2** [comment]
> gymnasium.error.NameNotFound: Environment `sumo-rl` doesn't exist.

have you fixed this issue? i have the same problem but don't how to solve this
